services:
  read:
    image: grafana/loki:2.8.3
    command:
      - "-config.file=/etc/loki/config.yaml"
      - "-target=read"
    ports:
      - "3101:3100"
      - 7946
      - 9095
    volumes:
      - ../observability/loki/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: &loki-dns
      javatuz:
        aliases:
          - loki

  write:
    image: grafana/loki:2.8.3
    command:
      - "-config.file=/etc/loki/config.yaml"
      - "-target=write"
    ports:
      - "3102:3100"
      - 7946
      - 9095
    volumes:
      - ../observability/loki/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      <<: *loki-dns

  promtail:
    image: grafana/promtail:2.8.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../observability/promtail/promtail-local-config.yaml:/etc/promtail/config.yaml
    command:
      - "-config.file=/etc/promtail/config.yaml"
    depends_on:
      - gateway
    extends:
      file: common-config.yaml
      service: network-deploy-service

  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 15s
      timeout: 20s
      retries: 5
    extends:
      file: common-config.yaml
      service: network-deploy-service

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - gateway
    entrypoint:
      - sh
      - -c
      - |
        mkdir -p /etc/grafana/provisioning/datasources 
        cat <<EOF> /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://gateway:3100
            jsonData:
              httpHeaderName1: "X-Scope-OrgID"
            secureJsonData:
              httpHeaderValue1: "tenant1"
        EOF
        /run.sh
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL","wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    extends:
      file: common-config.yaml
      service: network-deploy-service

  gateway:
    image: nginx:latest
    depends_on:
      - read
      - write
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF> /etc/nginx/nginx.conf
        user nginx;
        worker_processes 5; ## Default: 1
        
        events {
            worker_connections 1000; ## Default: 1024
        }
        
        http {
          resolver 127.0.0.11;
          
          server {
            listen 3100;
            
            location / {
                return 200 'OK';
                auth_basic off;
            }
      
            location /api/prom/push {
                proxy_pass http://write:3100\$$request_uri;
            }
      
            location ~ /api/prom/tail {
                proxy_pass http://read:3100\$$request_uri;
                proxy_set_header Upgrade \$$http_upgrade;
                proxy_set_header Connection "upgrade";
            }
      
            location ~ /api/prom/.* {
                proxy_pass http://read:3100\$$request_uri;
            }
      
            location = /loki/api/v1/push {
                proxy_pass http://write:3100\$$request_uri;
            }
            
            location = /loki/api/v1/tail {
                proxy_pass http://read:3100\$$request_uri;
                proxy_set_header Upgrade \$$http_upgrade;
                proxy_set_header Connection "upgrade";
            }
            
            location ~ /loki/api/.* {
                proxy_pass http://read:3100\$$request_uri;
            }
          }              
        }
        EOF
        /docker-entrypoint.sh nginx -g 'daemon off;'
    ports:
      - "3100:3100"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    extends:
      file: common-config.yaml
      service: network-deploy-service
          

  configserver:
    image: registry.hub.docker.com/guvalakat/configserver:s11
    container_name: configserver-ms
    ports:
      - "8071:8071"
    #   health checklar uchun
    #   readiness-state: servis tayyorligini tekshiradi
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s     # 10 soniyada bir marta tekshiradi
      timeout: 5s       # 5 soniyada javob qaytarishi kerak
      retries: 3        # 3 marta tekshiradi
      start_period: 10s # 10 soniyadan keyin tekshira boshlaydi
    extends:
      file: common-config.yaml
      service: microservice-base-config

  eurekaserver:
    image: registry.hub.docker.com/guvalakat/eurekaserver:s11
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    #   health checklar uchun
    #   readiness-state: servis tayyorligini tekshiradi
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s     # 10 soniyada bir marta tekshiradi
      timeout: 5s       # 5 soniyada javob qaytarishi kerak
      retries: 3        # 3 marta tekshiradi
      start_period: 10s # 10 soniyadan keyin tekshira boshlaydi
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"


  accounts:
    image: registry.hub.docker.com/guvalakat/accounts:s11
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s     # 10 soniyada bir marta tekshiradi
      timeout: 5s       # 5 soniyada javob qaytarishi kerak
      retries: 3        # 3 marta tekshiradi
      start_period: 30s # 10 soniyadan keyin tekshira boshlaydi
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config


  loans:
    image: registry.hub.docker.com/guvalakat/loans:s11
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent http://localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s     # 10 soniyada bir marta tekshiradi
      timeout: 5s       # 5 soniyada javob qaytarishi kerak
      retries: 3        # 3 marta tekshiradi
      start_period: 30s # 10 soniyadan keyin tekshira boshlaydi
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  cards:
    image: registry.hub.docker.com/guvalakat/cards:s11
    container_name: cards-ms
    ports:
      - "9001:9000"
    healthcheck:
      test: "curl --fail --silent http://localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s     # 10 soniyada bir marta tekshiradi
      timeout: 5s       # 5 soniyada javob qaytarishi kerak
      retries: 3        # 3 marta tekshiradi
      start_period: 30s # 10 soniyadan keyin tekshira boshlaydi
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  gatewayserver:
    image: registry.hub.docker.com/guvalakat/gatewayserver:s11
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

networks:
  javatuz:
    driver: bridge
